---
- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_connection != 'local'

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
  when: ansible_connection != 'local'

- name: Create application user
  ansible.builtin.user:
    name: "{{ app_user }}"
    shell: /bin/bash
    create_home: true
    system: true
  when: ansible_connection != 'local'

- name: Create application root directory
  ansible.builtin.file:
    path: "{{ app_root_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"
  when: ansible_connection != 'local'

- name: Optionally enable UFW and allow SSH and HTTP
  ansible.builtin.include_tasks: ufw.yml
  when: (enable_ufw | default(false)) | bool

