---
all:
  vars:
    ansible_user: dev_tf
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    
bastion:
  hosts:
    bastion-host:
      ansible_host: "{{ bastion_public_ip }}"  # Будет задан при запуске
      ansible_user: bastion
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

dev_servers:
  hosts:
    dev-vm1:
      ansible_host: 172.16.1.10  # Внутренний IP первой ВМ
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion@{{ bastion_public_ip }}"'
    dev-vm2:
      ansible_host: 172.16.1.11  # Внутренний IP второй ВМ
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion@{{ bastion_public_ip }}"'
  vars:
    # Общие переменные для dev серверов
    nginx_user: www-data
    nginx_worker_processes: auto
    nginx_worker_connections: 1024
    app_user: app
    app_group: app
    app_dir: /opt/app
    
web_servers:
  children:
    dev_servers: