- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when:
    - ansible_os_family == 'Debian'
    - not ansible_check_mode

- name: Install base packages
  apt:
    name:
      - git
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-apt
      - software-properties-common
    state: present
  when:
    - ansible_os_family == 'Debian'
    - not ansible_check_mode

- name: Ensure UFW installed when enabled
  apt:
    name: ufw
    state: present
  when:
    - ansible_os_family == 'Debian'
    - enable_ufw | bool
    - not ansible_check_mode

- name: Allow SSH in UFW
  ufw:
    rule: allow
    name: OpenSSH
  when:
    - ansible_os_family == 'Debian'
    - enable_ufw | bool

- name: Allow HTTP in UFW
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  when:
    - ansible_os_family == 'Debian'
    - enable_ufw | bool

- name: Allow HTTPS in UFW
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  when:
    - ansible_os_family == 'Debian'
    - enable_ufw | bool

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
  when:
    - ansible_os_family == 'Debian'
    - enable_ufw | bool

